name: PayMicro

on:
  push:
    branches:
     - develop
     - feature/cicd

  pull_request:
    branches:
      - develop
jobs:
  test:
    name: run-test
    runs-on: ubuntu-latest
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Copy .env
        run: php -r"file_exists('.env') || copy('.env.example', '.env');"
      - name: Run Composer
        run: |
            composer install -n --prefer-dist
        working-directory: ${{ github.workspace }}
      - name: Run test suite
        run: |
            php artisan test
      - name: Run Script
        run: echo 'Hola actions'

