name: PayMicro

on:
  push:
    branches:
     - develop
     - feature/cicd

  pull_request:
    branches:
      - develop
jobs:
  test:
    name: run-test
    runs-on: ubuntu-latest
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Run Script
        run: echo 'Hola actions'

